application: bdc-news
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/*
  script: app.application
- url: /*
  static_dir: public
- url: /feed/*
  static_dir: public/feed

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest