application: bdc-news
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: app.application
- url: /
  static_files: public/index.html
  upload: public/index.html
- url: /((\w+/)+)
  static_files: public/\1index.html
  upload: public/\1index.html
- url: /([\w/]+)
  static_files: public/\1/index.html
  upload: public/\1/index.html
- url: /
  static_dir: public

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest